name: Add membership application to membership GitHub roject

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add membership issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/rustfoundation/projects/2
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: "membership application"
