name: Test AreWeSafetyCriticalYet.org Deployment

on:
  pull_request_target:
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on
  merge_group:

permissions:
  contents: write
  pull-requests: write

jobs:
  test-deploy:
    name: Test AreWeSafetyCriticalYet.org Deployment
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: |
            arewesafetycriticalyet.org/package-lock.json

      - name: Install dependencies
        working-directory: arewesafetycriticalyet.org
        run: npm ci

      - name: Test build website
        working-directory: arewesafetycriticalyet.org
        env:
          BASE_URL: "/safety-critical-rust-consortium/pr-preview/pr-${{ github.event.pull_request.number }}/"
        run: npm run build
  
      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy PR to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./arewesafetycriticalyet.org/build
          destination_dir: "pr-preview/pr-${{ github.event.pull_request.number }}"
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
          keep_files: true

      - name: Publish the link in a PR comment
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "âœ… Temporary published at https://rustfoundation.github.io/safety-critical-rust-consortium/pr-preview/pr-${{ github.event.pull_request.number }}"
        env:
          GH_TOKEN: ${{ github.token }}
